"use client";

import { useState, useMemo } from "react";
import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  ArchiveBoxArrowDownIcon,
  ArchiveBoxIcon,
  ArchiveBoxXMarkIcon,
  ArrowDownCircleIcon,
  ArrowDownIcon,
  ArrowDownLeftIcon,
  ArrowDownOnSquareIcon,
  ArrowDownOnSquareStackIcon,
  ArrowDownRightIcon,
  ArrowDownTrayIcon,
  ArrowLeftCircleIcon,
  ArrowLeftEndOnRectangleIcon,
  ArrowLeftIcon,
  ArrowLeftOnRectangleIcon,
  ArrowLeftStartOnRectangleIcon,
  ArrowLongDownIcon,
  ArrowLongLeftIcon,
  ArrowLongRightIcon,
  ArrowLongUpIcon,
  ArrowPathIcon,
  ArrowPathRoundedSquareIcon,
  ArrowRightCircleIcon,
  ArrowRightEndOnRectangleIcon,
  ArrowRightIcon,
  ArrowRightOnRectangleIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowSmallDownIcon,
  ArrowSmallLeftIcon,
  ArrowSmallRightIcon,
  ArrowSmallUpIcon,
  ArrowsPointingInIcon,
  ArrowsPointingOutIcon,
  ArrowsRightLeftIcon,
  ArrowsUpDownIcon,
  ArrowTopRightOnSquareIcon,
  ArrowTrendingDownIcon,
  ArrowTrendingUpIcon,
  ArrowTurnDownLeftIcon,
  ArrowTurnDownRightIcon,
  ArrowTurnLeftDownIcon,
  ArrowTurnLeftUpIcon,
  ArrowTurnRightDownIcon,
  ArrowTurnRightUpIcon,
  ArrowTurnUpLeftIcon,
  ArrowTurnUpRightIcon,
  ArrowUpCircleIcon,
  ArrowUpIcon,
  ArrowUpLeftIcon,
  ArrowUpOnSquareIcon,
  ArrowUpOnSquareStackIcon,
  ArrowUpRightIcon,
  ArrowUpTrayIcon,
  ArrowUturnDownIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ArrowUturnUpIcon,
  AtSymbolIcon,
  BackspaceIcon,
  BackwardIcon,
  BanknotesIcon,
  Bars2Icon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3CenterLeftIcon,
  Bars3Icon,
  Bars4Icon,
  BarsArrowDownIcon,
  BarsArrowUpIcon,
  Battery0Icon,
  Battery100Icon,
  Battery50Icon,
  BeakerIcon,
  BellAlertIcon,
  BellIcon,
  BellSlashIcon,
  BellSnoozeIcon,
  BoldIcon,
  BoltIcon,
  BoltSlashIcon,
  BookmarkIcon,
  BookmarkSlashIcon,
  BookmarkSquareIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BugAntIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  BuildingOfficeIcon,
  BuildingStorefrontIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarDateRangeIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CameraIcon,
  ChartBarIcon,
  ChartBarSquareIcon,
  ChartPieIcon,
  ChatBubbleBottomCenterIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftEllipsisIcon,
  ChatBubbleLeftIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  ChatBubbleOvalLeftIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDoubleDownIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDoubleUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClipboardDocumentCheckIcon,
  ClipboardDocumentIcon,
  ClipboardDocumentListIcon,
  ClipboardIcon,
  ClockIcon,
  CloudArrowDownIcon,
  CloudArrowUpIcon,
  CloudIcon,
  CodeBracketIcon,
  CodeBracketSquareIcon,
  Cog6ToothIcon,
  Cog8ToothIcon,
  CogIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  CpuChipIcon,
  CreditCardIcon,
  CubeIcon,
  CubeTransparentIcon,
  CurrencyBangladeshiIcon,
  CurrencyDollarIcon,
  CurrencyEuroIcon,
  CurrencyPoundIcon,
  CurrencyRupeeIcon,
  CurrencyYenIcon,
  CursorArrowRaysIcon,
  CursorArrowRippleIcon,
  DevicePhoneMobileIcon,
  DeviceTabletIcon,
  DivideIcon,
  DocumentArrowDownIcon,
  DocumentArrowUpIcon,
  DocumentChartBarIcon,
  DocumentCheckIcon,
  DocumentCurrencyBangladeshiIcon,
  DocumentCurrencyDollarIcon,
  DocumentCurrencyEuroIcon,
  DocumentCurrencyPoundIcon,
  DocumentCurrencyRupeeIcon,
  DocumentCurrencyYenIcon,
  DocumentDuplicateIcon,
  DocumentIcon,
  DocumentMagnifyingGlassIcon,
  DocumentMinusIcon,
  DocumentPlusIcon,
  DocumentTextIcon,
  EllipsisHorizontalCircleIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  EqualsIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeDropperIcon,
  EyeIcon,
  EyeSlashIcon,
  FaceFrownIcon,
  FaceSmileIcon,
  FilmIcon,
  FingerPrintIcon,
  FireIcon,
  FlagIcon,
  FolderArrowDownIcon,
  FolderIcon,
  FolderMinusIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  ForwardIcon,
  FunnelIcon,
  GifIcon,
  GiftIcon,
  GiftTopIcon,
  GlobeAltIcon,
  GlobeAmericasIcon,
  GlobeAsiaAustraliaIcon,
  GlobeEuropeAfricaIcon,
  H1Icon,
  H2Icon,
  H3Icon,
  HandRaisedIcon,
  HandThumbDownIcon,
  HandThumbUpIcon,
  HashtagIcon,
  HeartIcon,
  HomeIcon,
  HomeModernIcon,
  IdentificationIcon,
  InboxArrowDownIcon,
  InboxIcon,
  InboxStackIcon,
  InformationCircleIcon,
  ItalicIcon,
  KeyIcon,
  LanguageIcon,
  LifebuoyIcon,
  LightBulbIcon,
  LinkIcon,
  LinkSlashIcon,
  ListBulletIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagnifyingGlassCircleIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassMinusIcon,
  MagnifyingGlassPlusIcon,
  MapIcon,
  MapPinIcon,
  MegaphoneIcon,
  MicrophoneIcon,
  MinusCircleIcon,
  MinusIcon,
  MinusSmallIcon,
  MoonIcon,
  MusicalNoteIcon,
  NewspaperIcon,
  NoSymbolIcon,
  NumberedListIcon,
  PaintBrushIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PauseCircleIcon,
  PauseIcon,
  PencilIcon,
  PencilSquareIcon,
  PercentBadgeIcon,
  PhoneArrowDownLeftIcon,
  PhoneArrowUpRightIcon,
  PhoneIcon,
  PhoneXMarkIcon,
  PhotoIcon,
  PlayCircleIcon,
  PlayIcon,
  PlayPauseIcon,
  PlusCircleIcon,
  PlusIcon,
  PlusSmallIcon,
  PowerIcon,
  PresentationChartBarIcon,
  PresentationChartLineIcon,
  PrinterIcon,
  PuzzlePieceIcon,
  QrCodeIcon,
  QuestionMarkCircleIcon,
  QueueListIcon,
  RadioIcon,
  ReceiptPercentIcon,
  ReceiptRefundIcon,
  RectangleGroupIcon,
  RectangleStackIcon,
  RocketLaunchIcon,
  RssIcon,
  ScaleIcon,
  ScissorsIcon,
  ServerIcon,
  ServerStackIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SignalIcon,
  SignalSlashIcon,
  SlashIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  Square2StackIcon,
  Square3Stack3DIcon,
  Squares2X2Icon,
  SquaresPlusIcon,
  StarIcon,
  StopCircleIcon,
  StopIcon,
  StrikethroughIcon,
  SunIcon,
  SwatchIcon,
  TableCellsIcon,
  TagIcon,
  TicketIcon,
  TrashIcon,
  TrophyIcon,
  TruckIcon,
  TvIcon,
  UnderlineIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserMinusIcon,
  UserPlusIcon,
  UsersIcon,
  VariableIcon,
  VideoCameraIcon,
  VideoCameraSlashIcon,
  ViewColumnsIcon,
  ViewfinderCircleIcon,
  WalletIcon,
  WifiIcon,
  WindowIcon,
  WrenchIcon,
  WrenchScrewdriverIcon,
  XCircleIcon,
  XMarkIcon,
} from "@heroicons/react/20/solid";
import type { ComponentType, SVGProps } from "react";

type HeroIcon = ComponentType<SVGProps<SVGSVGElement>>;

const COLORS = [
  "hsl(0, 65%, 55%)", "hsl(340, 60%, 55%)", "hsl(320, 50%, 55%)",
  "hsl(15, 70%, 55%)", "hsl(30, 65%, 55%)", "hsl(45, 60%, 55%)",
  "hsl(90, 40%, 48%)", "hsl(130, 40%, 45%)", "hsl(160, 45%, 42%)",
  "hsl(180, 45%, 45%)", "hsl(200, 60%, 50%)", "hsl(220, 60%, 55%)",
  "hsl(240, 50%, 58%)", "hsl(260, 50%, 55%)", "hsl(280, 45%, 55%)",
  "hsl(0, 0%, 45%)", "hsl(0, 0%, 25%)", "hsl(30, 10%, 55%)",
];

// Keys use kebab-case. Existing keys are preserved for backward compatibility.
export const ICON_MAP: Record<string, HeroIcon> = {
  "academic-cap": AcademicCapIcon,
  "adjustments-horizontal": AdjustmentsHorizontalIcon,
  "adjustments-vertical": AdjustmentsVerticalIcon,
  "archive-box-arrow-down": ArchiveBoxArrowDownIcon,
  "archive-box": ArchiveBoxIcon,
  "archive-box-x-mark": ArchiveBoxXMarkIcon,
  "arrow-down-circle": ArrowDownCircleIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-down-left": ArrowDownLeftIcon,
  "arrow-down-on-square": ArrowDownOnSquareIcon,
  "arrow-down-on-square-stack": ArrowDownOnSquareStackIcon,
  "arrow-down-right": ArrowDownRightIcon,
  download: ArrowDownTrayIcon,
  "arrow-left-circle": ArrowLeftCircleIcon,
  "arrow-left-end-on-rectangle": ArrowLeftEndOnRectangleIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-left-on-rectangle": ArrowLeftOnRectangleIcon,
  "arrow-left-start-on-rectangle": ArrowLeftStartOnRectangleIcon,
  "arrow-long-down": ArrowLongDownIcon,
  "arrow-long-left": ArrowLongLeftIcon,
  "arrow-long-right": ArrowLongRightIcon,
  "arrow-long-up": ArrowLongUpIcon,
  refresh: ArrowPathIcon,
  "arrow-path-rounded-square": ArrowPathRoundedSquareIcon,
  "arrow-right-circle": ArrowRightCircleIcon,
  "arrow-right-end-on-rectangle": ArrowRightEndOnRectangleIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-right-on-rectangle": ArrowRightOnRectangleIcon,
  "arrow-right-start-on-rectangle": ArrowRightStartOnRectangleIcon,
  "arrow-small-down": ArrowSmallDownIcon,
  "arrow-small-left": ArrowSmallLeftIcon,
  "arrow-small-right": ArrowSmallRightIcon,
  "arrow-small-up": ArrowSmallUpIcon,
  "arrows-pointing-in": ArrowsPointingInIcon,
  "arrows-pointing-out": ArrowsPointingOutIcon,
  "arrows-right-left": ArrowsRightLeftIcon,
  "arrows-up-down": ArrowsUpDownIcon,
  "arrow-top-right-on-square": ArrowTopRightOnSquareIcon,
  "arrow-trending-down": ArrowTrendingDownIcon,
  "arrow-trending-up": ArrowTrendingUpIcon,
  "arrow-turn-down-left": ArrowTurnDownLeftIcon,
  "arrow-turn-down-right": ArrowTurnDownRightIcon,
  "arrow-turn-left-down": ArrowTurnLeftDownIcon,
  "arrow-turn-left-up": ArrowTurnLeftUpIcon,
  "arrow-turn-right-down": ArrowTurnRightDownIcon,
  "arrow-turn-right-up": ArrowTurnRightUpIcon,
  "arrow-turn-up-left": ArrowTurnUpLeftIcon,
  "arrow-turn-up-right": ArrowTurnUpRightIcon,
  "arrow-up-circle": ArrowUpCircleIcon,
  "arrow-up": ArrowUpIcon,
  "arrow-up-left": ArrowUpLeftIcon,
  "arrow-up-on-square": ArrowUpOnSquareIcon,
  "arrow-up-on-square-stack": ArrowUpOnSquareStackIcon,
  "arrow-up-right": ArrowUpRightIcon,
  upload: ArrowUpTrayIcon,
  "arrow-uturn-down": ArrowUturnDownIcon,
  "arrow-uturn-left": ArrowUturnLeftIcon,
  "arrow-uturn-right": ArrowUturnRightIcon,
  "arrow-uturn-up": ArrowUturnUpIcon,
  "at-symbol": AtSymbolIcon,
  backspace: BackspaceIcon,
  backward: BackwardIcon,
  banknotes: BanknotesIcon,
  "bars-2": Bars2Icon,
  "bars-3-bottom-left": Bars3BottomLeftIcon,
  "bars-3-bottom-right": Bars3BottomRightIcon,
  "bars-3-center-left": Bars3CenterLeftIcon,
  "bars-3": Bars3Icon,
  "bars-4": Bars4Icon,
  "bars-arrow-down": BarsArrowDownIcon,
  "bars-arrow-up": BarsArrowUpIcon,
  "battery-0": Battery0Icon,
  battery: Battery100Icon,
  "battery-50": Battery50Icon,
  beaker: BeakerIcon,
  "bell-alert": BellAlertIcon,
  bell: BellIcon,
  "bell-slash": BellSlashIcon,
  "bell-snooze": BellSnoozeIcon,
  bold: BoldIcon,
  zap: BoltIcon,
  "bolt-slash": BoltSlashIcon,
  bookmark: BookmarkIcon,
  "bookmark-slash": BookmarkSlashIcon,
  "bookmark-square": BookmarkSquareIcon,
  book: BookOpenIcon,
  briefcase: BriefcaseIcon,
  "bug-ant": BugAntIcon,
  "building-library": BuildingLibraryIcon,
  "building-office-2": BuildingOffice2Icon,
  "building-office": BuildingOfficeIcon,
  "building-storefront": BuildingStorefrontIcon,
  cake: CakeIcon,
  calculator: CalculatorIcon,
  "calendar-date-range": CalendarDateRangeIcon,
  "calendar-days": CalendarDaysIcon,
  calendar: CalendarIcon,
  camera: CameraIcon,
  "chart-bar": ChartBarIcon,
  "chart-bar-square": ChartBarSquareIcon,
  "chart-pie": ChartPieIcon,
  "chat-bubble-bottom-center": ChatBubbleBottomCenterIcon,
  "chat-bubble-bottom-center-text": ChatBubbleBottomCenterTextIcon,
  "chat-bubble-left-ellipsis": ChatBubbleLeftEllipsisIcon,
  chat: ChatBubbleLeftIcon,
  "chat-bubble-left-right": ChatBubbleLeftRightIcon,
  "chat-bubble-oval-left-ellipsis": ChatBubbleOvalLeftEllipsisIcon,
  "chat-bubble-oval-left": ChatBubbleOvalLeftIcon,
  "check-badge": CheckBadgeIcon,
  "check-circle": CheckCircleIcon,
  check: CheckIcon,
  "chevron-double-down": ChevronDoubleDownIcon,
  "chevron-double-left": ChevronDoubleLeftIcon,
  "chevron-double-right": ChevronDoubleRightIcon,
  "chevron-double-up": ChevronDoubleUpIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up-down": ChevronUpDownIcon,
  "chevron-up": ChevronUpIcon,
  database: CircleStackIcon,
  "clipboard-document-check": ClipboardDocumentCheckIcon,
  "clipboard-document": ClipboardDocumentIcon,
  "clipboard-document-list": ClipboardDocumentListIcon,
  clipboard: ClipboardIcon,
  clock: ClockIcon,
  "cloud-arrow-down": CloudArrowDownIcon,
  "cloud-arrow-up": CloudArrowUpIcon,
  cloud: CloudIcon,
  code: CodeBracketIcon,
  "code-bracket-square": CodeBracketSquareIcon,
  settings: Cog6ToothIcon,
  "cog-8-tooth": Cog8ToothIcon,
  cog: CogIcon,
  terminal: CommandLineIcon,
  monitor: ComputerDesktopIcon,
  cpu: CpuChipIcon,
  "credit-card": CreditCardIcon,
  cube: CubeIcon,
  "cube-transparent": CubeTransparentIcon,
  "currency-bangladeshi": CurrencyBangladeshiIcon,
  "currency-dollar": CurrencyDollarIcon,
  "currency-euro": CurrencyEuroIcon,
  "currency-pound": CurrencyPoundIcon,
  "currency-rupee": CurrencyRupeeIcon,
  "currency-yen": CurrencyYenIcon,
  "cursor-arrow-rays": CursorArrowRaysIcon,
  "cursor-arrow-ripple": CursorArrowRippleIcon,
  phone2: DevicePhoneMobileIcon,
  "device-tablet": DeviceTabletIcon,
  divide: DivideIcon,
  "document-arrow-down": DocumentArrowDownIcon,
  "document-arrow-up": DocumentArrowUpIcon,
  "document-chart-bar": DocumentChartBarIcon,
  "document-check": DocumentCheckIcon,
  "document-currency-bangladeshi": DocumentCurrencyBangladeshiIcon,
  "document-currency-dollar": DocumentCurrencyDollarIcon,
  "document-currency-euro": DocumentCurrencyEuroIcon,
  "document-currency-pound": DocumentCurrencyPoundIcon,
  "document-currency-rupee": DocumentCurrencyRupeeIcon,
  "document-currency-yen": DocumentCurrencyYenIcon,
  "document-duplicate": DocumentDuplicateIcon,
  document: DocumentIcon,
  "document-magnifying-glass": DocumentMagnifyingGlassIcon,
  "document-minus": DocumentMinusIcon,
  "document-plus": DocumentPlusIcon,
  "document-text": DocumentTextIcon,
  "ellipsis-horizontal-circle": EllipsisHorizontalCircleIcon,
  "ellipsis-horizontal": EllipsisHorizontalIcon,
  "ellipsis-vertical": EllipsisVerticalIcon,
  mail: EnvelopeIcon,
  "envelope-open": EnvelopeOpenIcon,
  equals: EqualsIcon,
  "exclamation-circle": ExclamationCircleIcon,
  "exclamation-triangle": ExclamationTriangleIcon,
  "eye-dropper": EyeDropperIcon,
  eye: EyeIcon,
  "eye-slash": EyeSlashIcon,
  "face-frown": FaceFrownIcon,
  smile: FaceSmileIcon,
  film: FilmIcon,
  "finger-print": FingerPrintIcon,
  flame: FireIcon,
  flag: FlagIcon,
  "folder-arrow-down": FolderArrowDownIcon,
  folder: FolderIcon,
  "folder-minus": FolderMinusIcon,
  "folder-open": FolderOpenIcon,
  "folder-plus": FolderPlusIcon,
  forward: ForwardIcon,
  funnel: FunnelIcon,
  gif: GifIcon,
  gift: GiftIcon,
  "gift-top": GiftTopIcon,
  globe: GlobeAltIcon,
  "globe-americas": GlobeAmericasIcon,
  "globe-asia-australia": GlobeAsiaAustraliaIcon,
  "globe-europe-africa": GlobeEuropeAfricaIcon,
  h1: H1Icon,
  h2: H2Icon,
  h3: H3Icon,
  "hand-raised": HandRaisedIcon,
  "hand-thumb-down": HandThumbDownIcon,
  like: HandThumbUpIcon,
  hash: HashtagIcon,
  heart: HeartIcon,
  home: HomeIcon,
  "home-modern": HomeModernIcon,
  identification: IdentificationIcon,
  "inbox-arrow-down": InboxArrowDownIcon,
  inbox: InboxIcon,
  "inbox-stack": InboxStackIcon,
  "information-circle": InformationCircleIcon,
  italic: ItalicIcon,
  key: KeyIcon,
  language: LanguageIcon,
  lifebuoy: LifebuoyIcon,
  lightbulb: LightBulbIcon,
  link: LinkIcon,
  "link-slash": LinkSlashIcon,
  "list-bullet": ListBulletIcon,
  lock: LockClosedIcon,
  unlock: LockOpenIcon,
  "magnifying-glass-circle": MagnifyingGlassCircleIcon,
  search: MagnifyingGlassIcon,
  "magnifying-glass-minus": MagnifyingGlassMinusIcon,
  "magnifying-glass-plus": MagnifyingGlassPlusIcon,
  map: MapIcon,
  "map-pin": MapPinIcon,
  megaphone: MegaphoneIcon,
  mic: MicrophoneIcon,
  "minus-circle": MinusCircleIcon,
  minus: MinusIcon,
  "minus-small": MinusSmallIcon,
  moon: MoonIcon,
  music: MusicalNoteIcon,
  newspaper: NewspaperIcon,
  "no-symbol": NoSymbolIcon,
  "numbered-list": NumberedListIcon,
  "paint-brush": PaintBrushIcon,
  send: PaperAirplaneIcon,
  "paper-clip": PaperClipIcon,
  "pause-circle": PauseCircleIcon,
  pause: PauseIcon,
  edit: PencilIcon,
  pencil: PencilSquareIcon,
  "percent-badge": PercentBadgeIcon,
  "phone-arrow-down-left": PhoneArrowDownLeftIcon,
  "phone-arrow-up-right": PhoneArrowUpRightIcon,
  phone: PhoneIcon,
  "phone-x-mark": PhoneXMarkIcon,
  photo: PhotoIcon,
  "play-circle": PlayCircleIcon,
  play: PlayIcon,
  "play-pause": PlayPauseIcon,
  "plus-circle": PlusCircleIcon,
  plus: PlusIcon,
  "plus-small": PlusSmallIcon,
  power: PowerIcon,
  "presentation-chart-bar": PresentationChartBarIcon,
  "presentation-chart-line": PresentationChartLineIcon,
  printer: PrinterIcon,
  puzzle: PuzzlePieceIcon,
  "qr-code": QrCodeIcon,
  "question-mark-circle": QuestionMarkCircleIcon,
  "queue-list": QueueListIcon,
  radio: RadioIcon,
  "receipt-percent": ReceiptPercentIcon,
  "receipt-refund": ReceiptRefundIcon,
  "rectangle-group": RectangleGroupIcon,
  layers: RectangleStackIcon,
  rocket: RocketLaunchIcon,
  rss: RssIcon,
  scale: ScaleIcon,
  scissors: ScissorsIcon,
  server: ServerIcon,
  "server-stack": ServerStackIcon,
  share: ShareIcon,
  shield: ShieldCheckIcon,
  "shield-exclamation": ShieldExclamationIcon,
  "shopping-bag": ShoppingBagIcon,
  "shopping-cart": ShoppingCartIcon,
  signal: SignalIcon,
  "signal-slash": SignalSlashIcon,
  slash: SlashIcon,
  sparkles: SparklesIcon,
  volume: SpeakerWaveIcon,
  "speaker-x-mark": SpeakerXMarkIcon,
  "square-2-stack": Square2StackIcon,
  "square-3-stack-3d": Square3Stack3DIcon,
  grid: Squares2X2Icon,
  "squares-plus": SquaresPlusIcon,
  star: StarIcon,
  "stop-circle": StopCircleIcon,
  stop: StopIcon,
  strikethrough: StrikethroughIcon,
  sun: SunIcon,
  palette: SwatchIcon,
  "table-cells": TableCellsIcon,
  tag: TagIcon,
  ticket: TicketIcon,
  trash: TrashIcon,
  trophy: TrophyIcon,
  truck: TruckIcon,
  tv: TvIcon,
  underline: UnderlineIcon,
  "user-circle": UserCircleIcon,
  "user-group": UserGroupIcon,
  user: UserIcon,
  "user-minus": UserMinusIcon,
  "user-plus": UserPlusIcon,
  users: UsersIcon,
  variable: VariableIcon,
  "video-camera": VideoCameraIcon,
  "video-camera-slash": VideoCameraSlashIcon,
  "view-columns": ViewColumnsIcon,
  "viewfinder-circle": ViewfinderCircleIcon,
  wallet: WalletIcon,
  wifi: WifiIcon,
  window: WindowIcon,
  wrench: WrenchIcon,
  "wrench-screwdriver": WrenchScrewdriverIcon,
  "x-circle": XCircleIcon,
  "x-mark": XMarkIcon,
};

const ALL_KEYS = Object.keys(ICON_MAP);

export default function GroupIconPicker({
  color,
  icon,
  onColorChange,
  onIconChange,
}: {
  color: string;
  icon: string;
  onColorChange: (color: string) => void;
  onIconChange: (icon: string) => void;
}) {
  const [search, setSearch] = useState("");

  const displayedIcons = useMemo(() => {
    if (!search.trim()) return ALL_KEYS;
    const q = search.toLowerCase().replace(/\s+/g, "-");
    return ALL_KEYS.filter((name) => name.includes(q));
  }, [search]);

  return (
    <div className="flex w-52 flex-col gap-2">
      {/* Colors */}
      <div className="flex flex-wrap gap-1">
        {COLORS.map((c) => (
          <button
            key={c}
            onClick={() => onColorChange(c)}
            className="flex h-4 w-4 cursor-pointer items-center justify-center rounded-full transition-transform hover:scale-110"
            style={{ backgroundColor: c }}
          >
            {c === color && (
              <CheckIcon className="h-2 w-2 text-white" />
            )}
          </button>
        ))}
      </div>

      {/* Search */}
      <div className="flex items-center gap-1.5 rounded-md bg-zinc-100 px-2 py-1">
        <MagnifyingGlassIcon className="h-3 w-3 text-zinc-400" />
        <input
          type="text"
          placeholder="Search icons..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="flex-1 bg-transparent text-xs text-zinc-700 placeholder:text-zinc-400 outline-none"
        />
      </div>

      {/* Icons */}
      <div className="grid grid-cols-7 gap-0.5 max-h-48 overflow-x-hidden overflow-y-auto [scrollbar-width:thin]">
        {displayedIcons.map((key) => {
          const Icon = ICON_MAP[key];
          const isActive = key === icon;
          return (
            <button
              key={key}
              title={key}
              onClick={() => onIconChange(key)}
              className={`flex h-7 w-7 shrink-0 cursor-pointer items-center justify-center rounded-md transition-colors ${
                isActive
                  ? "text-white"
                  : "text-zinc-500 hover:bg-zinc-100"
              }`}
              style={isActive ? { backgroundColor: color } : undefined}
            >
              <Icon className="h-3.5 w-3.5" />
            </button>
          );
        })}
      </div>
    </div>
  );
}
