import { db } from "@/services/db";
import { tags } from "@/db/schema";
import { eq, and, asc } from "drizzle-orm";

export const getTagsForUser = async (userId: string) => {
  return db
    .select()
    .from(tags)
    .where(and(eq(tags.createdBy, userId), eq(tags.isAutoGenerated, false)))
    .orderBy(asc(tags.createdAt));
};
