import { db } from "@/services/db";
import { groups } from "@/db/schema";
import { eq, and, asc } from "drizzle-orm";

export const getGroupsForUser = async (userId: string) => {
  return db
    .select()
    .from(groups)
    .where(and(eq(groups.createdBy, userId), eq(groups.isAutoGenerated, false)))
    .orderBy(asc(groups.createdAt), asc(groups.id));
};
